[config]
generate_terminal = true

[wallpaper]
command = "swww"
arguments = ["img"]
set = true

[templates.kitty]
input_path = "./templates/kitty.conf"
output_path = "~/.config/kitty/colors-matugen.conf"
post_hook = "pkill -SIGUSR1 -x kitty"

